theme: jekyll-theme-architect

title: Vwifi
description: Wifi Simulator on GNS3
show_downloads: true
github:
  zip_url: https://github.com/Raizo62/vwifi/archive/refs/heads/master.zip
  tar_url : https://github.com/Raizo62/vwifi/archive/refs/heads/master.zip
  repository_url : https://github.com/Raizo62/vwifi
